//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirlineProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFlight_Details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblFlight_Details()
        {
            this.tblFlight_Schedule = new HashSet<tblFlight_Schedule>();
        }
    
        public int Flight_ID { get; set; }
        public Nullable<int> FC_Capacity { get; set; }
        public Nullable<int> BC_Capacity { get; set; }
        public Nullable<int> EC_Capacity { get; set; }
        public string status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblFlight_Schedule> tblFlight_Schedule { get; set; }
    }
}
