//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirlineProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSeat_Details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblSeat_Details()
        {
            this.tblPassenger_Details = new HashSet<tblPassenger_Details>();
        }
    
        public int Seat_ID { get; set; }
        public Nullable<int> Schedule_ID { get; set; }
        public string Seat_No { get; set; }
        public string Seat_Class { get; set; }
        public string Seat_Status { get; set; }
        public Nullable<int> Receipt_ID { get; set; }
    
        public virtual tblFlight_Schedule tblFlight_Schedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPassenger_Details> tblPassenger_Details { get; set; }
        public virtual tblTicket_Details tblTicket_Details { get; set; }
    }
}
